# Generated by Django 4.2.5 on 2023-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwalletdetails',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='balance1',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='balance_usd',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='live_bitcoin_price',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='live_bitcoin_price1',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='total_received',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='total_received1',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='total_received_usd',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='total_sent',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='total_sent1',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='total_sent_usd',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userwalletdetails',
            name='transactions',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
    ]
