# Generated by Django 4.2.5 on 2023-10-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_formsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwalletdetails',
            name='live_bitcoin_price1',
        ),
    ]
